% TTCREATEMONITOR   Create a TrueTime monitor.
%
%  Usage: ttCreateMonitor(name, display)
%
%  Inputs:
%    name      Name of the monitor, must be unique.
%    display   0 or 1, to indicate if the monitor should be included
%              in the monitor graph generated by the simulation.
%       
% See also TTENTERMONITOR, TTEXITMONITOR, TTCREATEEVENT
%
%       TrueTime, Version 1.5
%       Copyright (c) 2007
%       Martin Ohlin, Dan Henriksson and Anton Cervin
%       Department of Automatic Control LTH
%       Lund University, Sweden
